language: emacs-lisp

before_install:
      - sudo add-apt-repository -y ppa:cassou/emacs
      - sudo apt-get update -qq
      - sudo apt-get -f install
      - sudo apt-get install -qq emacs24 emacs24-el

install: true

before_script: true

script:
      - make compile
      - make test